service: Assessment-demo

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  timeout: 15
  stage: dev
  region: us-east-1 

functions:
  fetchDetails:
    handler: dist/handler.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      port: 3000
      baseDir: ''
      customer_details_bucket: customer-shipping-details
      csv_file_name: customers_shipping_addresses.csv
      accessKeyId: ${env:AWS_ACCESS_KEY_ID}
      secretAccessKey: ${env:AWS_SECRET_ACCESS_KEY}
      response_csv_file_name: response_tracker.csv
      region: 'us-east-1'

resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: customers-details
        AccessControl: Private
        VersioningConfiguration:
          Status: Enabled

package:
  exclude:
    - .git/**
