name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Deploys on push to main branch
    paths-ignore:
      - 'test/**'  
  pull_request:
    branches:
      - main  # Deploys on pull request to main branch
    paths-ignore:
      - 'test/**'  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: npx serverless deploy --stage dev
